### ISSUE TITLE
Integrate Avalanche

### ISSUE THREAD

**Issue by gauthier-voron** [NatoliChris/diablo-benchmark#10]
IT could be interesting to integrate Avalanche

**Comment by lebdron** [comment]
The task here is to write the deployment scripts. Avalanche supports Ethererum API, so the following config file works:
```yaml
name: "ethereum"
nodes:
  - 127.0.0.1:9650/ext/bc/C/ws
key_file: "./scripts/sample/keys.json"
window: 3
```
