### ISSUE TITLE
[BUG] Solana does not run properly for 1000 tx/s

### ISSUE THREAD

**Issue by gauthier-voron** [NatoliChris/diablo-benchmark#20]
**Describe the bug**
A benchmark of Solana on 4 nodes + 1 diablo node for 1000 tx/s for 2 minutes does not work (i.e. takes 12 minutes to produce a 0 tx/s throughput result)

**To Reproduce**
Clone minion script (commit: 95cfd11982b5480d3fb743b5d6a57c6f4318c5bc)
Checkout develop branch
Spawn 5 machines: `./bin/minion boot --verbose --key=your-key --size=5 --region=eu-central-1`
Change the 'install-diablo' script so it fetches develop branch (and remove old install before `git clone`)
Run solana: `./bin/minion run --verbose --install=install-solana --install=install-solang solana --install=install-diablo workload-1000.yaml the-fleet-id`
with 'workload-1000.yaml' being:
```
name: "Workload 1000"
description: "Constant 1000 tps"
secondaries: 0
threads: 0
bench:
  type: "simple"
  txs:
    0:   1000
    119: 1000
```

**Expected behavior**
Produces a result directory with non zero throughput in less than 20 minutes
